config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects do
    resources :targets, only: [:new, :index] do
      collection do
        get :edit_all
        put :update_all
      end
    end
    resources :tasks, only: [:new, :index]
  end
  resources :targets, only: [:create, :show, :update, :edit] do
    resources :health_attributes, only: [:new]
  end
  resources :tasks, only: [:create, :show, :update, :edit] do
    put :pickup
    put :done, :archive
  end
  resources :health_attributes

  get  '/default_health_ratings/import', to: 'default_health_ratings#import',     as: 'import_default_health_ratings'
  post '/default_health_ratings/import', to: 'default_health_ratings#import_csv', as: ''

  ActiveAdmin.routes(self)
  devise_for :users
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :project
  belongs_to :target_type, optional: true
  has_many :health_attributes

  validates :name, presence: true
end

app/models/target_type.rb
class TargetType < ApplicationRecord
  has_many :targets
  has_many :default_health_attributes

  def icon_name
    case name
    when 'Terrestrial Ecosystem'
      'globe-africa'
    when 'Freshwater Ecosystem'
      'tint'
    when 'Marine/Estuarine Ecosystem'
      'fish'
    when 'Animal Species or Assemblage'
      'paw'
    when 'Plant Species or Community'
      'tree'
    else
      'question'
    end
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :load_target, only: %i[edit show update]
  before_action :load_project, only: %i[index create new edit_all update_all]

  def index
    @targets = @project.targets
  end

  def new
    @target = Target.new
    add_breadcrumb 'New Target', new_project_target_path(@project)
  end

  def edit
    add_breadcrumb 'Edit', edit_target_path(@target)
  end

  def show; end

  def create
    @target = Target.new(target_params)
    if @target.save
      TargetService.new(@target).create
      flash[:notice] = 'Target created'
      redirect_to target_path(@target)
    else
      flash.now[:alert] = @target.errors.full_messages
      render :new
    end
  end

  def update
    if @target.update(target_params)
      flash[:notice] = 'Target updated'
      redirect_to project_targets_url(@target.project)
    else
      flash.now[:alert] = @target.errors.full_messages
      render :edit
    end
  end

  def edit_all
    @targets = @project.targets
  end

  def update_all
    @targets = @project.targets.index_by(&:id)

    params[:targets].each do |id, target_params|
      @targets[id.to_i].update! target_params.permit!
    end

    redirect_to [@project, :targets]
  end

  private

  def load_target
    @target = Target.find params[:id]
    @project = @target.project
    add_breadcrumb @project.name, project_path(@project)
    add_breadcrumb 'Targets', project_targets_path(@project)
    add_breadcrumb @target.name, target_path(@target)
  end

  def load_project
    @project = Project.find params[:project_id]
    add_breadcrumb @project.name, project_path(@project)
    add_breadcrumb 'Targets', project_targets_path(@project)
  end

  def target_params
    target_params = params.require(:target)
                          .permit(:name, :description, :target_type_id)
    target_params.merge(project_id: params[:project_id])
  end
end

app/views/targets/_form.html.erb
<section class="form-section">
  <%= form_for(@target) do |f| %>
    <h2 class="heading page-heading"><%= heading %></h2>
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-field" %>
    <%= f.label :target_type_id, class: "form-label" %>
    <%= f.collection_select(:target_type_id, TargetType.all, :id, :name, {prompt: true}, {class: 'form-field'}) %>
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: 'form-field' %>
    <%= hidden_field_tag 'project_id', @project.id %>

    <div class="form-footer">
      <%= f.submit 'Save', class: 'button-primary' %>
    </div>
  <% end %>
  <%= render partial: 'hints' %>
</section>

app/views/targets/_hints.html.erb
<aside class="hints">
  <section class="hint">
    <h3>Start with Ecosystem Targets</h3>
    <p>
      Use a “coarse-filter/ fine-filter” approach to identifying conservation targets. First, focus on the selection of
      ecological systems or communities. These act as the "coarse-filter" that capture most species of special interest.
      If you conserve the ecosystems at your area, you will conserve these species at your area. (Species of special
      interest will be listed later as “Nested Targets.”).
      Then, teams may need to add species with unique ecological requirements or threats that are not already reflected
      by the ecological systems in which they are embedded. These are considered “fine-filter” targets with special
      conservation needs that go beyond conserving the ecosystem.
    </p>
  </section>
  <section class="hint">
    <h3>Lumping vs. Splitting Targets</h3>
    <p>
      When in doubt, lump co-occurring targets. It’s easy enough to split out the targets later if needed. Examples:
      rare fish assemblage; longleaf pine woodland and associated communities.
    </p>
  </section>
  <section class="hint">
    <h3>Migratory Species as Targets</h3>
    <p>
      If migratory birds, fish or other animal species are selected as targets, the life-stage of the species at the
      project area should be explicitly identified as the target. A project team cannot be responsible for conserving a
      species across its range, but rather only for that part of the species life cycle when it resides in the
      project area. Turbo-CAP also suggests that project teams make the habitat the target rather than the species
      itself – e.g. Mule deer wintering habitat instead over Over-wintering mule deer.
    </p>
  </section>
  <section class="hint">
    <h3>Keystone Species</h3>
    <p>
      “Keystone” species are species that drive major ecological processes; if it were removed the ecosystem would
      change dramatically. Keystone species may be “apex predators” (e.g., wolves in Yellowstone, major herbivores
      (e.g., elephants in African savanna), or filters (e.g., oysters in Chesapeake Bay).
    </p>
  </section>
  <section class="hint">
    <h3>Umbrella Species and Focal Species</h3>
    <p>
      An “umbrella” species is a species that has habitat needs which reflect the needs of many other species in the
      area, and as such is selected to represent many species, or even an ecosystem. For example, the greater sage
      grouse is often considered an umbrella species for its associated sagebrush ecosystems – i.e., if the sage grouse
      population is healthy in an area, its ecosystems are most likely to be healthy (but perhaps not some other
      sagebrush obligate species that have special requirements). Similarly, “focal” species involves choosing a
      suite of species within a landscape whose functional requirements collectively encompass those of most other
      species in the landscape. turboCAP recommends caution - there is some scientific debate on using umbrella species
      and focal species for conservation planning.
    </p>
  </section>
</aside>

app/views/targets/edit.html.erb
<%= render partial: 'form', locals: {heading: "Edit #{@target.name}"} %>

app/views/targets/edit_all.html.erb
<%= form_tag update_all_project_targets_path(@project), method: :put do |f| %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>

    <tbody>
      <% @targets.each do |target| %>
        <tr>
          <td><%= text_field_tag "targets[#{target.id}][name]", target.name %></td>
          <td><%= text_area_tag "targets[#{target.id}][description]", target.description %></td>
          <td><%= select_tag "targets[#{target.id}][target_type_id]", options_from_collection_for_select(TargetType.all, :id, :name, target.target_type_id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= submit_tag 'Save' %>
<% end %>

app/views/targets/index.html.erb
<section class="page-section">
  <header class="page-header">
    <h2 class="heading page-heading">Targets</h2>
    <%= link_to 'Edit all', edit_all_project_targets_path(@project), class: 'navigation' %>
  </header>
  <% if @targets.empty? %>
    <p>No Targets yet</p>
  <% else %>
    <table class="index-table">
      <thead>
      <tr>
        <th/>
        <th>Name</th>
        <th>Description</th>
        <th>Type</th>
      </tr>
      </thead>

      <tbody>
      <% @targets.each do |target| %>
        <tr>
          <td class="icon" aria-hidden="true">
            <%= fa_icon target.target_type&.icon_name || 'question' %>
          </td>
          <th><%= link_to target.name, target_path(target), class: 'navigation' %></th>
          <td><%= target.description %></td>
          <td><%= target.target_type&.name %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
  <div class="form-footer">
    <%= link_to(new_project_target_path(@project.id), class: 'navigation') do %>
      <%= fa_icon 'plus' %>
      Add New Target
    <% end %>
  </div>
</section>

app/views/targets/new.html.erb
<%= render partial: 'form', locals: {heading: 'Create a New Target'} %>

app/views/targets/show.html.erb
<section class="page-section">
  <header class="page-header">
    <h2 class="heading page-heading"><%= fa_icon @target.target_type&.icon_name, 'aria-hidden' => true %>  <%= @target.name %></h2>
    <%= link_to 'Edit', edit_target_path(@target),
                class: 'navigation',
                id: "edit-target-#{@target.id}",
                'aria-label' => "Edit Target #{@target.name}" %>
  </header>
  <section class="health-attributes">
    <h3>Health Attributes</h3>
    <table class="index-table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Rating</th>
        <th/>
      </tr>
      </thead>
      <tbody>
      <% @target.health_attributes.each do |health_attr| %>
        <tr>
          <th scope="row"><%= link_to health_attr.name, health_attribute_path(health_attr) %></th>
          <td/>
          <td>
            <%= link_to('Delete', health_attr, method: :delete, id: "delete-health-attribute-#{health_attr.id}") %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>»
    <%= link_to(new_target_health_attribute_path(@target.id), class: 'navigation') do %>
      <%= fa_icon 'plus' %>
      Add Health Attribute
    <% end %>
  </section>
</section>