config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects do
    resources :targets, only: [:new, :index] do
      collection do
        get :edit_all
        put :update_all
      end
    end
    resources :tasks, only: [:new, :index]
  end
  resources :targets, only: [:create, :show, :update, :edit] do
    resources :health_attributes, only: [:new]
  end
  resources :tasks, only: [:create, :show, :update, :edit] do
    put :pickup
    put :done, :archive
  end
  resources :health_attributes

  get  '/default_health_ratings/import', to: 'default_health_ratings#import',     as: 'import_default_health_ratings'
  post '/default_health_ratings/import', to: 'default_health_ratings#import_csv', as: ''

  ActiveAdmin.routes(self)
  devise_for :users
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user, optional: true

  validates :name, presence: true
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :load_task, only: %i[edit show update]
  before_action :load_project, only: %i[index create new]

  def new
    @task = @project.tasks.new
    @users = User.all
  end

  def create
    @task = @project.tasks.new(task_params)
    @task.status = 'New'
    if @task.save
      redirect_to @task.project
    else
      render 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to @task.project
    else
      render 'edit'
    end
  end

  def pickup
    @task = Task.find(params[:task_id])
    if @task.update(user: current_user, status: 'In Progress')
      redirect_to @task.project
    else
      render 'edit'
    end
  end

  def done
    @task = Task.find(params[:task_id])
    if @task.update(status: 'Done')
      redirect_to @task.project
    else
      render 'edit'
    end
  end

  def archive
    @task = Task.find(params[:task_id])
    if @task.update(status: 'Archived')
      redirect_to @task.project
    else
      render 'edit'
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description,
                                 :due_on, :project_id, :user_id)
  end

  def load_task
    @task = Task.find params[:id]
  end

  def load_project
    @project = Project.find params[:project_id]
  end
end

app/views/tasks/_form.html.erb
<section class="form-section">
  <%= form_for @task do |f| %>
    <h2 class="heading page-heading"><%= heading %></h2>
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: 'form-field' %>
    <%= f.label :due_on, class: "form-label" %>
    <%= f.date_field :due_on, class: 'form-field' %>
    <%= f.label :user, class: "form-label" %>
    <%= f.collection_select :user_id, User.all, :id, :email, {include_blank: ""}, {class: 'form-field'} %>
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: 'form-field' %>

    <%= hidden_field_tag 'project_id', @project.id %>

    <div class="form-footer">
      <%= f.submit "Add Task", class: 'button-primary' %>
    </div>
  <% end %>
</section>

app/views/tasks/_index.html.erb
<header class="page-header">
  <h2 class="heading page-heading">Tasks</h2>
</header>
<% if @tasks.empty? %>
  <p>No Tasks yet</p>
<% else %>
  <table class="index-table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Assigned To</th>
      <th>Status</th>
      <th>Due Date</th>
      <th>Description</th>
    </tr>
    </thead>

    <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <th><%= link_to "#{task.name}", task_path(task), class: 'navigation' %></th>
        <td><%= task.user&.email %></td>
        <td><%= task.status %></td>
        <td><%= task.due_on %></td>
        <td><%= task.description %></td>
        <td>
          <% if current_user && task.user_id.nil? %>
            <%= button_to 'Pick-Up Task', task_pickup_path(task), id: "pickup-task-#{task.id}", method: :put %>
            <%= button_to 'X', task_archive_path(task), id: "archive-task-#{task.id}", method: :put %>
          <% end %>
          <% if current_user && task.user_id == current_user.id && task.status == 'In Progress' %>
            <%= button_to 'Done', task_done_path(task), id: "done-task-#{task.id}", method: :put %>
            <%= button_to 'X', task_archive_path(task), id: "archive-task-#{task.id}", method: :put %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to(new_project_task_path(@project.id), class: 'navigation') do %>
  <%= fa_icon 'plus' %>
  Add New Task
<% end %>

app/views/tasks/edit.html.erb
<%= render partial: 'form', locals: {heading: "Edit #{@task.name}"} %>

app/views/tasks/new.html.erb
<%= render partial: 'form', locals: {heading: 'Create a New Task'} %>