config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects do
    resources :targets, only: [:new, :index] do
      collection do
        get :edit_all
        put :update_all
      end
    end
    resources :tasks, only: [:new, :index]
  end
  resources :targets, only: [:create, :show, :update, :edit] do
    resources :health_attributes, only: [:new]
  end
  resources :tasks, only: [:create, :show, :update, :edit] do
    put :pickup
    put :done, :archive
  end
  resources :health_attributes

  get  '/default_health_ratings/import', to: 'default_health_ratings#import',     as: 'import_default_health_ratings'
  post '/default_health_ratings/import', to: 'default_health_ratings#import_csv', as: ''

  ActiveAdmin.routes(self)
  devise_for :users
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :targets, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_and_belongs_to_many :users, dependent: :destroy

  validates :name, presence: true
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :load_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
  end

  def show
    @tasks = @project.tasks.reject do |task|
      task.status == 'Archived'
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = 'Project created'
      redirect_to @project
    else
      flash.now[:alert] = @project.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @project.update_attributes(project_params)
      flash[:notice] = 'Project updated'
      redirect_to @project
    else
      flash.now[:alert] = @project.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @project.destroy!
      flash[:notice] = 'Project deleted'
      redirect_to projects_path
    else
      flash.now[:alert] = @project.errors.full_messages
      redirect_to projects_path
    end
  end

  private

  def load_project
    @project = Project.find(params[:id])
    add_breadcrumb 'Projects', :projects_path
    add_breadcrumb @project.name, project_path(@project)
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/views/projects/_form.html.erb
<section class="form-section">
  <%= form_with(model: project, local: true) do |f| %>
    <h2 class="heading"><%= heading %></h2>
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-field' %>

    <%= f.label :description, class: 'form-label' %>
    <%= f.text_area :description, class: 'form-field' %>


    <div class="form-footer">
      <%= f.submit 'Save', class: 'button-primary' %>
    </div>
  <% end %>
</section>

app/views/projects/edit.html.erb
<%= render 'form', heading: "Editing #{@project.name}", project: @project %>

app/views/projects/index.html.erb
<section class="page-section">
  <h1>Projects</h1>
  <table class="index-table">
    <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @projects.each do |project| %>
      <tr>
        <th scope="row"><%= link_to project.name, project, class: 'navigation' %></th>
        <td><%= project.description %></td>
        <td><%= link_to 'Delete', project, method: :delete, class: 'delete', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="form-footer">
    <%= link_to(new_project_path, class: 'navigation')  do %>
      <%= fa_icon 'plus' %>
      Add New Project
    <% end %>
  </div>
</section>

app/views/projects/new.html.erb
<%= render 'form', heading: 'Create a New Project', project: @project %>

app/views/projects/show.html.erb
<section class="page-section" >
  <%= render partial: 'tasks/index' %>
</section>