config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects do
    resources :targets, only: [:new, :index] do
      collection do
        get :edit_all
        put :update_all
      end
    end
    resources :tasks, only: [:new, :index]
  end
  resources :targets, only: [:create, :show, :update, :edit] do
    resources :health_attributes, only: [:new]
  end
  resources :tasks, only: [:create, :show, :update, :edit] do
    put :pickup
    put :done, :archive
  end
  resources :health_attributes

  get  '/default_health_ratings/import', to: 'default_health_ratings#import',     as: 'import_default_health_ratings'
  post '/default_health_ratings/import', to: 'default_health_ratings#import_csv', as: ''

  ActiveAdmin.routes(self)
  devise_for :users
end

app/views/layouts/_alert_header.html.erb
<header class="alert-header">
  <% if alert_type == 'notice' %>
    Success!
  <% elsif alert_type == 'alert' %>
    Whoops! Something is not right...
  <% else %>
    Information
  <% end %>
</header>

app/views/layouts/_app_header.html.erb
<header class="app-header">
  <div class="app-header-content">
    <a href="/"><img class="logo" alt="turboCAP" src=<%= asset_path('turbocap-logo.png') %>/></a>
    <% if user_signed_in? %>
      <div class="user-dropdown">
        <button class="dropbtn">
          <%= fa_icon 'user' %> <%= fa_icon 'caret-down' %>
        </button>
        <ul class="user-dropdown-content">
          <li class="user-dropdown-item">
            <b>Signed in as: </b>
            <%= current_user.email %>
          </li>
          <% if current_user.admin? %>
            <li class="user-dropdown-item">
              <%= link_to(admin_dashboard_path, class: 'navigation') do %>
                <%= fa_icon 'user-circle' %>
                Admin
              <% end %>
            </li>
           <% end %>
          <li class="user-dropdown-item">
            <%= link_to(destroy_user_session_path, method: :delete, class: 'navigation', id: 'sign-out-link') do %>
              <%= fa_icon 'sign-out-alt' %>
              Sign out
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/_flash_messages.html.erb
<% if flash.present? %>
  <div class="flash">
    <% flash.each do |key, msg| %>
      <% if msg %>
        <div class="alert-<%= key %> alert">
          <% if key == 'notice' %>
            <%= fa_icon 'check-circle', class: 'alert-icon'  %>
          <% elsif key == 'alert' %>
            <%= fa_icon 'exclamation-circle', class: 'alert-icon' %>
          <% else %>
            <%= fa_icon 'info-circle' %>
          <% end %>
          <div class="alert-body">
            <%= render 'layouts/alert_header', alert_type: key %>
            <% if msg.kind_of? Array %>
              <ul class="alert-msg-list">
                <% msg.each do |m| %>
                  <li><%= m %></li>
                <% end %>
              </ul>
            <% else %>
              <%= msg %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_import_button_partial.html.erb
<div>
  <div class="col-md-6 col-md-offset-3 table-curved">
    <table class="table table-condensed table-responsive">
      <tr>
        <td>
          <strong>FILE UPLOAD</strong>
        </td>
      </tr>
      <tr>
        <td>
          <%=  form_tag({action: :import}, multipart: true) do %>
            <%= file_field_tag 'file_upload', id: "file_upload" %>
            <%= submit_tag("Upload") %>
          <% end %>
        </td>
      </tr>
    </table>
    <!--</div>-->
  </div>
</div>

<script>
    $(document).on('change', '.btn-file :file', function() {
        var input = $(this),
            numFiles = input.get(0).files ? input.get(0).files.length : 1,
            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.trigger('fileselect', [numFiles, label]);
    });

    $(document).ready( function() {
        $('.btn-file :file').on('fileselect', function(event, numFiles, label) {

            var input = $(this).parents('.input-group').find(':text'),
                log = numFiles > 1 ? numFiles + ' files selected' : label;

            if( input.length ) {
                input.val(log);
            } else {
                if( log ) alert(log);
            }

        });
    });
</script>

app/views/layouts/_project.html.erb
<div class="site-wrapper project-view">
  <aside class="status-sidebar">
    <header class="sidebar-header">
      <div class="project-image" aria-hidden="true"></div>
      <h1 class="project-heading">
        <%= link_to @project.name, project_url(@project), class: 'project-heading-link' %>
      </h1>
      <%= link_to 'Edit Project', edit_project_path(@project),
                  class: 'navigation',
                  id: "edit-project-#{  @project.id}",
                  'aria-label' => "edit project #{@project.name}"%>
    </header>
    <div class="next-event">
      <div class="date">
        <div class="month">Aug</div>
        18
      </div>
      <div class="event-details">
        <h3 class="heading has-sidelines">Next Meeting</h3>
        Teleconference at 3pm CST
        <a href="">[more info]</a>
      </div>
    </div>
  </aside>
  <main>
    <nav class="nav-bar">
      <%= link_to(project_targets_url(@project), class: target_tab?) do %>
        <span>Capture</span> <em>Targets</em>
      <% end %>
      <a href=""><span>Describe</span> <em>Target Health</em></a>
      <a href=""><span>Identify</span> <em>Threats</em></a>
      <a href=""><span>Develop</span> <em>Strategies</em></a>
      <a href=""><span>Complete</span> <em>Assessment</em></a>
    </nav>
    <%= yield %>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboCap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag    'application' %>
    <%= stylesheet_pack_tag    'application' %>
    <%= favicon_link_tag asset_path('turbocap-logo.png'), :rel => 'icon', :type =>  'image/png' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Zilla+Slab:300i, 500,600,600i,700" rel="stylesheet">
  </head>

  <body>
    <%= render partial: 'layouts/app_header' %>
    <%= render partial: 'layouts/flash_messages' %>
    <% if !current_user %>
      <%= yield %>
    <% else %>
      <div class="breadcrumbs">
        <%= render_breadcrumbs %>
      </div>
      <section class="main-section">
        <% if @project&.valid? %>
          <%= render layout: 'layouts/project' do %>
              <%= yield %>
          <% end %>
        <% else %>
          <%= yield %>
        <% end %>
      </section>
    <% end %>
  </body>
</html>